version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: postgres_db
    environment:
      POSTGRES_DB: stefanini
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./postgres-init:/docker-entrypoint-initdb.d
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5

  wiremock:
    image: wiremock/wiremock:3.13.0
    container_name: cep_api
    ports:
      - "8082:8080"
    volumes:
      - ./wiremock:/home/wiremock  # pasta com os mapeamentos e stubs
    command: [ "--global-response-templating", "--verbose" ]

  app:
    build: .
    container_name: spring_app
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/stefanini
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 123456
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      API_CEP_BASE_URL: http://wiremock:8080/ceps/
    ports:
      - "8084:8084"
    depends_on:
      postgres:
        condition: service_healthy
      wiremock:
        condition: service_started

volumes:
  postgres_data:
