server:
  port: 8084
  servlet:
    context-path: '/api/'

spring:
  application:
    name: poc
  datasource:
    url:  ${SPRING_DATASOURCE_URL}   #jdbc:postgresql://postgres-stefanini :5432/stefanini
    username: ${SPRING_DATASOURCE_USERNAME} #postgres
    password: ${SPRING_DATASOURCE_USERNAME} #123456
  jpa:
    hibernate:
      ddl-auto: ${SPRING_JPA_HIBERNATE_DDL_AUTO} #update
      dialect: org.hibernate.dialect.PostgreSQLDialect
      jdbc:
        lob.non-contextual-creation: true
    properties:
      hibernate:
        show_sql: true

logging:
  level:
    com.stefanini: info
#    root: debug

app:
  cep:
    url: ${API_CEP_BASE_URL} #http://localhost:8082/ceps/



